spring:
  datasource:
    url: jdbc:mysql://localhost:3306/santa_secret?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: admin
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    contexts: default
    changeLog: classpath:/db/db.changelog-master.xml
  application:
    name: api-santa-secret